<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="7" total="8" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="2334" started-at="2021-04-27T04:01:29Z" finished-at="2021-04-27T04:01:32Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="2334" started-at="2021-04-27T04:01:29Z" finished-at="2021-04-27T04:01:32Z">
      <class name="AlertAware.api.test.SignIn">
        <test-method status="PASS" signature="verifyTwoFactorAuthWithInvalidCredentials()[pri:8, instance:AlertAware.api.test.SignIn@548a9f61]" name="verifyTwoFactorAuthWithInvalidCredentials" duration-ms="2297" started-at="2021-04-27T00:01:29Z" finished-at="2021-04-27T00:01:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyTwoFactorAuthWithInvalidCredentials -->
      </class> <!-- AlertAware.api.test.SignIn -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
